### PR TITLE
Just warn on regeneration (not error)

### LINKED ISSUE #3: It should be possible to regenerate $n$ test files without restarting the tests $n$ times
When I change the output of my function to produce a different string,
then I know that all of my reference tests are going to fail.

So I delete my 5 test files.

Now, to recreate them I have to rerun julia 5 times.
because after recreating the test files it throws an error.

 I think instead of throwing an error it should do something the `testset` can catch.
Like maybe an `@test false` or an `@test_broken false` ?

### PR DESCRIPTION
**Pull request by oxinabox**
Closes #3 

I needed to regenerate like 30 reference tests or something.
This made it not utter suffering.

Though having some kind of setting (maybe an environment variables) for "Replace all nonmatching",
might be good.

### CODE REVIEW

File: src/string.jl [hunk 1]
```diff
@@ -60,8 +60,10 @@ function test_reference_string(file::File, actual::AbstractArray{<:AbstractStrin
                 answer = first(readline())
                 if answer == 'y'
                     write(path, join(actual, "\n"))
+                    warn("Please run the tests again for any changes to take effect")
+                else
+                    @test false
```
Comment (Evizero) [inline src/string.jl]: this will still abort the test run after the testset is done, no?

Comment (oxinabox) [reply src/string.jl]: If there is no further enclosing testset, yes.
(This is why it is good to have one ottermost testset with your package name IMO).

But this is only if the answer is 'n'.
And if I've said _No, do not regenerate the test files_
then that is an actual failure

Comment (Evizero) [reply src/string.jl]: right, good point

**Comment by Evizero** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/15374
