### PR TITLE
enhance `test_reference` API and support Number type

### LINKED ISSUE #25: Is it possible to add a Number/Real only test case with tolerance argument?
I tried to use ReferenceTests in the recent development of ImageDistances.jl, but it would directly throw errors even if there's an insignificant numerical difference

```diff
Test for "CIEDE2000_Color1.txt" failed.
DIFF ------------------------
-"900.000068665732"
+"900.000063800018"
```

which is just caused by Float32 <--> Float64 accuracy issue

I can try to work on it if it’s possible( without much efforts)

### PR DESCRIPTION
**Pull request by johnnychen94**
Changes:

* keep two keyword arguments: `render` and `test`(new)
* add util `number_test` to compare numbers (closes #25 )
* *heavily* rewrite the docstring ⚠️

By exposing `test` to users, they're free to define other comparison methods and pass it to `@test_reference`. For example, 

```julia
# add an absolute tolerance for numbers comparison
@test_reference "references/string3.txt" 1338 test=number_test(10)

# use PSNR for images comparison
@test_reference "references/camera.png" testimage("cameraman") test=(x,y)->psnr(x,y)>25
```

RFC:

* `psnr` comes from [`ImageQualityIndexes`](https://github.com/JuliaImages/ImageQualityIndexes.jl), which is lighter than `Images`. Shall we replace `Images.@test_approx_eq_sigma_eps` with this to remove the direct dependency on `Images`?

### CODE REVIEW

**Comment by Evizero** [comment]
Thank you for working on this package.

This sounds like a good idea. Replacing the dependency on `Images.@test_approx_eq_sigma_eps` certainly is something we talked about before

I am not really active in julia right now, and I am a bit rusty with this codebase. So I am hoping for @oxinabox to review this, if he has the time. If not, please feel free to ping me after a couple days or so.

File: src/handlers.jl [hunk 1]
```diff
@@ -1,68 +1,77 @@
...
+    catch err
+        if err isa ErrorException
+            return false
+        else
+            rethrow()
         end
     end
 end
 
+function test_reference(file::File, actual::AbstractArray{<:Colorant}; test = default_image_test, render = BeforeAfterImage())
```
Comment (johnnychen94) [inline src/handlers.jl]: API changed:

`sigma` and `eps` are deleted here. I believe nobody is using these two keywords, so I didn't make any deprecation here.

**Comment by oxinabox** [comment]
I will try and review this this week, but I am at a conference, so limited time

**Comment by oxinabox** [comment]
I think I like the concept.


 first glance:

Why add a kwarg arg?  Convention is for functions argd make them the first arg so do blocks work.
I guess it does mean more methods to define, but it isn't too bad, they can be oneliners.

Do you think calling it `test` will get confusing? How about `equality_measure` or even `equiv` which is currently used?

Can we put these into their own file? With a name matching what we call the argument? E.g. `equality_mesures.jl`

**Comment by johnnychen94** [comment]
> I guess maybe for the macro kwarg works better, no do block there anyway.

That's why I use kwarg instead of the first arg here. 

> Do you think calling it `test` will get confusing? How about `equality_measure` or even `equiv` which is currently used?

I have similar feelings here. The first version I use `equiv` but it looks strange. `equality_measure` is a little bit lengthy here; most test cases are supposed to be fit in one line. I'm thinking of `measure`, `key` or `by` as an alternative.

> Can we put these into their own file? With a name matching what we call the argument?

Of course. I can do it later.

**Comment by johnnychen94** [comment]
bump

File: src/test_reference.jl [hunk 2]
```diff
@@ -1,37 +1,85 @@
 """
-    @test_reference filename ex [kw...]
+    @test_reference filename ex [test] [render]
```
Comment (oxinabox) [inline src/test_reference.jl]: Not really changed by this PR
but we should change `ex` to `expr`
since `ex` couild be `exception`, or `example`

File: src/equality_metrics.jl [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+```julia
+# string3.txt is "1337"
+@test_reference "references/string3.txt" 1338 # failed
+# set absolute tolorance 10
+@test_reference "references/string3.txt" 1338 test=number_test(10) # pass
+```
+"""
+function number_test(eps = eps(Float64))
+    return (ref, x) -> abs(ref - x) <= eps
+end
```
Comment (oxinabox) [inline src/equality_metrics.jl]: rather than `eps` say `atol`.
Maybe rewrite to use `isapprox`,
and to thus accept `atol` and `rtol` ?


Then call it `approx_equality` ?

File: src/equality_metrics.jl [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+function default_image_test(reference, actual)
```
Comment (oxinabox) [inline src/equality_metrics.jl]:
```suggestion
function default_image_equality(reference, actual)
```

**Comment by oxinabox** [comment]
Lets call the kwarg `by` rather than `test`,
And lets suffix the functions used with `equality` rather than `test`.
So rather than `default_image_test` we have `default_image_equality`

I think the follow looks right:
```
@test_reference "references/img.png" myimage by=default_image_equality
```

File: src/handlers.jl [hunk 5]
```diff
@@ -1,68 +1,68 @@
...
+    _test_reference(test, render, file, str)
 end
 
 # --------------------------------------------------------------------
 # SHA as string
 
-function test_reference(file::File{format"SHA256"}, actual)
-    test_reference(file, string(actual))
+function test_reference(file::File{format"SHA256"}, actual; test = nothing, render = BeforeAfterFull())
+    test === nothing || throw(ArgumentError("SHA256 file type doesn't support keyword `test`."))
```
Comment (oxinabox) [inline src/handlers.jl]: do we need this?

File: src/test_reference.jl [hunk 6]
```diff
@@ -45,6 +93,12 @@ cases.
 # Images can also be stored as hash. Note however that this
 # can only check for equality (no tolerance possible)
 @test_reference "references/camera.sha256" testimage("cameraman")
+
+# test images using ImageQualityIndexes.PSNR
+@test_reference "references/camera.png" testimage("cameraman") by=(x,y)->:psnr(x,y)>25
```
Comment (johnnychen94) [inline src/test_reference.jl]: Is it possible to skip `:` here in the macro? For example,
```julia
@test_reference "references/camera.png" testimage("cameraman") by=(x,y)->psnr(x,y)>25
```

**Comment by johnnychen94** [comment]
The next PR I'm thinking of is to replace current `default_image_equality` with a simple `psnr` implementation so that we can replace `Images` by `ImageCore`. Some simple test says that `Images.@ test_approx_eq_sigma_eps` approximately is equivalent to `PSNR>t` where `t` is around 25-30.

Is it safe to do such a replacement? @Evizero

File: src/test_reference.jl (hunk 6 above)
Comment (oxinabox) [reply src/test_reference.jl]: hmm should be. Lets fix that.
Seems like maybe you are missing an `esc`?

Comment (johnnychen94) [reply src/test_reference.jl]: :( Unfortunately,  I'm not familiar with macros, can you make a patch to it?

Looks like we need to rewrite the `@test_reference` so that `psnr` is evaluated before passing to `test_reference`.

https://github.com/Evizero/ReferenceTests.jl/blob/41a61f2c05d96ea5a97443eae87a057146957377/src/test_reference.jl#L50-L58

Comment (oxinabox) [reply src/test_reference.jl]: I think it just needs to be
```
 macro test_reference(reference, actual, kws...) 
     dir = Base.source_dir() 
     expr = :(test_reference(abspath(joinpath($dir, $(esc(reference)))), $(esc(actual)))) 
     for kw in kws 
         (kw isa Expr && kw.head == :(=)) || error("invalid signature for @test_reference") 
         k, v = kw.args
         push!(expr.args, Expr(:kw, k, esc(v))) 
     end 
     expr 
 end 
```

**Comment by Evizero** [comment]
I'd go with a depwarn what is happening and once some time passes we remove the warning and the dependency

**Comment by oxinabox** [comment]
LGTM :shipit:

**Comment by oxinabox** [comment]
Oh did we want to do something about those deprecations first?

I am kinda down with just shipping this as a breaking change without deprecation.
But I am fairly gung-ho about that.

**Comment by johnnychen94** [comment]
How do you think the current arbitrary `kw...` API? I feel like limit it to `by` is the best strategy here since nobody's actually using `render` at present, and expose it when we find a good use case.

**Comment by oxinabox** [comment]
> How do you think the current arbitrary kw... API? I feel like limit it to by is the best strategy here since nobody's actually using render at present, and we can expose it when we find a good use case.

I think leave it as is.
but don't document anything except `by`.

Keeps the implementation simple.

**Comment by johnnychen94** [comment]
I simplified the docstring by removing contents related to `render` and rebased the commits. I think it's ready to merge.

**Comment by oxinabox** [comment]
@Evizero  how do you feel about not deprecating?
It shouldn't break anyone as they will all have upper bounded.
(since that was imposed on the whole registry since our last release)

**Comment by Evizero** [comment]
I leave this to you. I have complete faith in your opinion.
